version: '3'
services:
  php:
    container_name: ubuntu-php
    build: php/.
    image: php-compose
    volumes:
      - /home/moises/docker/projetos-php/:/var/www/html
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=unix$DISPLAY
    devices:
      - /dev/dri 
  mysql:
    container_name: ubuntu-mysql
    build: mysql/.
    image: mysql-compose