version: '3'
services:
  # php_5:
  #   container_name: php_5.6
  #   build: php/.
  #   image: php-compose
  #   volumes:
  #     - /home/moises/docker/projetos-php/:/var/www/html
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   environment:
  #     - DISPLAY=unix$DISPLAY
  #   devices:
  #     - /dev/dri 
  # mysql:
  #   container_name: mysql
  #   build: mysql/.
  #   image: mysql-compose
  node_js:
    container_name: node
    build: node/.
    image: node-compose
    volumes:
      - /home/moises/docker/projetos-node/:/home/user/projetos
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=unix$DISPLAY
    devices:
      - /dev/dri
      - /dev/snd
    links:
      - mongo:mongo
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    build: mongo/.
    image: mongo-compose
      